### ISSUE TITLE
Can't add a new meeting nor have current meetings list displayed on webpage.

### ISSUE THREAD

**Issue by guy762** [meeting-guide/12-step-meeting-list#39]
I attempted to add a new meeting. It would not preview nor publish. Both Preview Changes and Update Buttons were grayed out. When I put in the address for the new meeting location the map would only display the whole planet not the address location.

I went back the main meeting list. I saw the new meeting I was working on, but it was in draft mode and it did not have the address nor day of the meeting saved.

I was able to successfully view and preview all the other listed meetings and view them on the main meeting list webpage.

I then decided to deactivate and then re-activate the plugin. When I did this, now all the meetings will view internally, but I can't preview them. They would all throw a page not found error. Also, the main meeting list webpage will not display.

Well, I thought, I can't make things worse by uninstalling and re-installing the plugin. I backed up my data and uninstalled the plugin. I then re-installed the plugin and imported my data successfully. Same issues. I cannot create and save a new meeting, nor can I preview/view any of the meeting pages that were re-imported.

The main meeting list page still does not display. I did not update any other plugins or anything else before this issue occurred. The night before this issue occurred I was able to successfully add a meeting.

**Comment by joshreisner** [comment]
Hi, this isn't a great venue for support, much better to post over here on the support threads: https://wordpress.org/support/plugin/12-step-meeting-list/

That said, it sounds like you're having a geocoding issue, the plugin needs to look up your meeting's address after you enter it. I recommend carefully entering the address and clicking off of the field, so that the map registers it properly.

Also if you're having a javascript problem (sometimes other plugins can cause this) that can interfere with geocoding. If you want to check your broswer's javascript console that can tell you more info, or you can try disabling other plugins. The Events Calendar is a common culprit.

Finally, WordPress does have some issues with 404s when you install / reinstall plugins, you can usually solve these by going to Settings > Permalinks and hitting "Save Changes."

If you have further issues please post on the main support threads. Thanks
